apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: multi-component-child-zinf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: multi-component-child-zinf
    app.kubernetes.io/part-of: build-suite-component-update-vdfi
  name: multi-component-child-zinamct
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: multi-component-child-zinf
    weight: 100
status: {}
